# Generated by Django 2.2.4 on 2019-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
