version: '3.7'

services:

  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=@^r7%+ajfq4my-e^cymbs26ah&*$a*y$$j_n3g4a&5+zghtn#i
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_JiImaA2FElgKpEdVbL6poCWT00hDIuqUkf
      - STRIPE_TEST_SECRET_KEY=sk_test_YZiGdAxgs9SUI9MjRy0YPNCr00oZ5ckzG5
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db: 
    image: postgres:11
    


