version: '3.7'

services:

  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
    env_file: .env

    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db
  
  db:
    image: postgres:10
    env_file: .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    # ports:
    #   - 4000
    networks:
      - nginx_network
    depends_on:
      - web
  
networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: