version: '3.7'

services:

  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
    env_file: .env

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:10
    env_file: .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  


volumes:
  postgres_data: