version: '3.7'

services:

  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  db:
    image: postgres:10
    env_file: .env.db


volumes:
  postgres_data:
  



    


