# Generated by Django 2.2.1 on 2019-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='title',
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
