# Generated by Django 2.2.4 on 2019-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190704_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='type',
        ),
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('type', 'type')], default='size', max_length=50),
        ),
        migrations.AddField(
            model_name='variation',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
