# Generated by Django 2.2.4 on 2019-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191108_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('abc', 'abc'), ('liquid', 'liquid'), ('cloth', 'cloth')], default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='variation',
            name='types',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
