# Generated by Django 2.2.4 on 2019-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191108_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
